// <auto-generated />
using System;
using AgileTicketSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgileTicketSystem.Migrations
{
    [DbContext(typeof(TicketContext))]
    [Migration("20200712173624_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgileTicketSystem.Models.Sprint", b =>
                {
                    b.Property<string>("SprintID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SprintName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SprintID");

                    b.ToTable("Redo_Sprints");

                    b.HasData(
                        new
                        {
                            SprintID = "T-1",
                            SprintName = "Ticket-1"
                        },
                        new
                        {
                            SprintID = "T-2",
                            SprintName = "Ticket-2"
                        },
                        new
                        {
                            SprintID = "T-3",
                            SprintName = "Ticket-3"
                        },
                        new
                        {
                            SprintID = "T-4",
                            SprintName = "Ticket-4"
                        },
                        new
                        {
                            SprintID = "T-5",
                            SprintName = "Ticket-5"
                        });
                });

            modelBuilder.Entity("AgileTicketSystem.Models.Status", b =>
                {
                    b.Property<string>("StatusID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusID");

                    b.ToTable("Redo_Statuses");

                    b.HasData(
                        new
                        {
                            StatusID = "N",
                            StatusName = "New"
                        },
                        new
                        {
                            StatusID = "I",
                            StatusName = "In Progress"
                        },
                        new
                        {
                            StatusID = "Q",
                            StatusName = "Quality Assurance Review"
                        },
                        new
                        {
                            StatusID = "C",
                            StatusName = "Complete"
                        },
                        new
                        {
                            StatusID = "R",
                            StatusName = "Revisit"
                        });
                });

            modelBuilder.Entity("AgileTicketSystem.Models.Ticket", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("PointValue")
                        .HasColumnType("int");

                    b.Property<string>("SprintId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TicketDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicketID");

                    b.HasIndex("SprintId");

                    b.HasIndex("StatusId");

                    b.ToTable("Redo_Tickets");
                });

            modelBuilder.Entity("AgileTicketSystem.Models.Ticket", b =>
                {
                    b.HasOne("AgileTicketSystem.Models.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId");

                    b.HasOne("AgileTicketSystem.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");
                });
#pragma warning restore 612, 618
        }
    }
}
